### ISSUE TITLE
dockerzulip_zulip_1 exited with code 1

### ISSUE THREAD

**Issue by cmcneil** [Galexrt/docker-zulip#19] opened 2015-10-21 18:20 UTC
Hello! I'm not sure whether this is a problem with the config, a problem with the documentation, or my own misunderstanding, but advice would be greatly appreciated :). (And thanks again for this repo!)

STEPS TO REPRODUCE:
----------------------------------
- Stop and remove all docker containers.
- Clone a fresh repository.
- Make the following changes to `docker-compose.yml`
  - s/example\.com/mydomain\.org/g
  - Switch the ports from 80:80 -> 8080:80, and 443:443 -> 8443:443, to expose zulip on different host ports.
- Run `docker-compose up` (as root)

VERSION INFO:
----------------------
- Docker version 1.8.3, build f4bf5c7
- docker-compose version: 1.5.0rc1
- Host System(I can't imagine this is relevant): Linux leviathan 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt9-3~deb8u1 (2015-04-24) x86_64 GNU/Linux

ERROR LINES:
--------------------
zulip_1     | subprocess.CalledProcessError: Command '['/home/zulip/deployments/current/bin/log-management-command', '/home/zulip/deployments/current/manage.py checkconfig']' returned non-zero exit status 1
dockerzulip_zulip_1 exited with code 1

FULL ERROR OUTPUT:
---------------------------------
zulip_1     | Zulip settings setup done.
zulip_1     | Setting up database settings and server ...
database_1  | 2015-10-21 18:20:55 UTC [41-1] zulip@zulip ERROR:  permission denied to create role
database_1  | 2015-10-21 18:20:55 UTC [41-2] zulip@zulip STATEMENT:  CREATE USER zulip;
zulip_1     | Waiting for database server to allow connectionsERROR:  permission denied to create role
zulip_1     | ALTER ROLE
database_1  | 2015-10-21 18:20:55 UTC [41-3] zulip@zulip ERROR:  database "zulip" already exists
database_1  | 2015-10-21 18:20:55 UTC [41-4] zulip@zulip STATEMENT:  CREATE DATABASE zulip OWNER=zulip;
zulip_1     | ERROR:  database "zulip" already exists
database_1  | 2015-10-21 18:20:55 UTC [41-5] zulip@zulip ERROR:  schema "zulip" already exists
zulip_1     | ERROR:  schema "zulip" already exists
database_1  | 2015-10-21 18:20:55 UTC [41-6] zulip@zulip STATEMENT:  CREATE SCHEMA zulip AUTHORIZATION zulip;
database_1  | 2015-10-21 18:20:55 UTC [42-1] zulip@zulip ERROR:  permission denied to create extension "tsearch_extras"             [16/338]
database_1  | 2015-10-21 18:20:55 UTC [42-2] zulip@zulip HINT:  Must be superuser to create this extension.
database_1  | 2015-10-21 18:20:55 UTC [42-3] zulip@zulip STATEMENT:  CREATE EXTENSION tsearch_extras SCHEMA zulip;
zulip_1     | ERROR:  permission denied to create extension "tsearch_extras"
zulip_1     | HINT:  Must be superuser to create this extension.
zulip_1     | Database setup done.
zulip_1     | Checking zulip config ...
zulip_1     | Traceback (most recent call last):
zulip_1     |   File "/home/zulip/deployments/current/bin/log-management-command", line 10, in <module>
zulip_1     |     file_handler = logging.FileHandler(settings.MANAGEMENT_LOG_PATH)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
zulip_1     |     self._setup(name)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
zulip_1     |     self._wrapped = Settings(settings_module)
zulip_1     |   File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
zulip_1     |     mod = importlib.import_module(self.SETTINGS_MODULE)
zulip_1     |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
zulip_1     |     __import__(name)
zulip_1     |   File "/home/zulip/deployments/current/bin/../zproject/settings.py", line 31, in <module>
zulip_1     |     secrets_file.read("/etc/zulip/zulip-secrets.conf")
zulip_1     |   File "/usr/lib/python2.7/ConfigParser.py", line 305, in read
zulip_1     |     self._read(fp, filename)
zulip_1     |   File "/usr/lib/python2.7/ConfigParser.py", line 512, in _read
zulip_1     |     raise MissingSectionHeaderError(fpname, lineno, line)
zulip_1     | ConfigParser.MissingSectionHeaderError: File contains no section headers.
zulip_1     | file: /etc/zulip/zulip-secrets.conf, line: 1
zulip_1     | "email_password = '12345'\n"
zulip_1     | Traceback (most recent call last):
zulip_1     |   File "/home/zulip/deployments/current/manage.py", line 14, in <module>
zulip_1     |     " ".join(sys.argv)])
zulip_1     |   File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
zulip_1     |     raise CalledProcessError(retcode, cmd)
zulip_1     | subprocess.CalledProcessError: Command '['/home/zulip/deployments/current/bin/log-management-command', '/home/zulip/deployments/current/manage.py checkconfig']' returned non-zero exit status 1
dockerzulip_zulip_1 exited with code 1

**Comment by Galexrt** [comment] 2015-10-21 19:45
Error seems to be the `entrypoint.sh` writing the secrets badly formatted in the `/etc/zulip/zulip-secrets.conf` file (the secrets file is linked to `/data/zulip-secrets.conf`.

This will be fixed in the new release with Zulip version 1.3.7.
While using the current `dev` image, I didn't got this error, but I have to test this a bit more.

**Comment by Galexrt** [comment] 2015-10-21 22:53
This error seems to be fixed in the Zulip version 1.3.7. At least I can't reproduce this error using the v1.3.7 version.

Can you please try again with the latest version and report back if it worked now?
Please report back even when this issue is closed. Thanks!

Closing, because I can't reproduce it anymore using the latest version (v1.3.7).

**Closed by Galexrt** 2015-10-21 22:53 UTC
Labels: bug, fixed

**Comment by cmcneil** [comment] 2015-10-22 00:33
Yep, seems to be fixed with 1.3.7! Unfortunately the same procedure for replication above now produces a different error. (django.db.utils.InternalError: could not open dictionary file "/usr/share/postgresql/9.4/tsearch_data/en_us.dict": No such fil
e or directory)

I guess I'll open a different bug for that.
