### ISSUE TITLE
Cannot search history message

### ISSUE THREAD

**Issue by bluesalt** [galexrt/docker-zulip#48] opened 2015-11-10 13:35 UTC
From the error logs  I saw
```
2015-11-10 08:13:48,575 ERROR    Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/decorator.py", line 85, in wrapper
    return func(request, *args, **kwargs)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/decorator.py", line 474, in _wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/decorator.py", line 301, in _wrapped_view_func
    return authenticate_log_and_execute_json(request, view_func, *args, **kwargs)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/decorator.py", line 290, in authenticate_log_and_execute_json
    return view_func(request, user_profile, *args, **kwargs)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/views/messages.py", line 78, in json_get_old_messages
    return get_old_messages_backend(request, user_profile)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/decorator.py", line 474, in _wrapped_view_func
    return view_func(request, *args, **kwargs)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/views/messages.py", line 542, in get_old_messages_backend
    query_result = list(sa_conn.execute(query).fetchall())
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 662, in execute
    params)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 761, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 874, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1024, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 196, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 867, in _execute_context
    context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 324, in do_execute
    cursor.execute(statement, parameters)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/lib/db.py", line 23, in execute
    return wrapper_execute(self, super(TimeTrackingCursor, self).execute, query, vars)
  File "/home/zulip/deployments/2015-11-07-23-02-08/zerver/lib/db.py", line 11, in wrapper_execute
    return action(sql, params)
ProgrammingError: (ProgrammingError) function ts_match_locs_array(unknown, text, tsquery) does not exist
LINE 2: ...ECT message_id, flags, subject, rendered_content, ts_match_l...

HINT:  No function matches the given name and argument types. You might need to add explicit type casts. 'SELECT /* get_old_messages */ anon_1.message_id, anon_1.flags, anon_1.subject, anon_1.rendered_content, anon_1.content_matches, anon_1.subject_matches \nFROM (SELECT message_id, flags, subject, rendered_content, ts_match_locs_array(%(param_1)s, rendered_content, plainto_tsquery(%(param_2)s, %(param_3)s)) AS content_matches, ts_match_locs_array(%(param_4)s, escape_html(subject), plainto_tsquery(%(param_2)s, %(param_3)s)) AS subject_matches \nFROM zerver_usermessage JOIN zerver_message ON zerver_usermessage.message_id = zerver_message.id \nWHERE user_profile_id = %(param_5)s AND (search_tsvector @@ plainto_tsquery(%(param_2)s, %(param_3)s)) AND message_id <= %(message_id_1)s ORDER BY message_id DESC \n LIMIT %(param_6)s) AS anon_1 ORDER BY message_id ASC' {'param_5': 7, 'param_4': 'zulip.english_us_search', 'param_6': 100, 'param_1': 'zulip.english_us_search', 'param_3': u'dummy', 'param_2': 'zulip.english_us_search', 'message_id_1': 17}
```

Seems it is related with the tsearch. Not sure if we have this tsearch-extras dependency installed correctly or not.  Does the search feature work well in your environment?

**Comment by Galexrt** [comment] 2015-11-10 13:41
Do you use the `galexrt/zulip-postgresql-tsearchextras` for database?

**Comment by bluesalt** [comment] 2015-11-10 14:26
Yes, here is the containers list:
```
d0eb0d4745b3        quay.io/galexrt/zulip:v1.3.7-2                          "/entrypoint.sh app:r"   24 hours ago        Up 24 hours         0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   dockerzulip_zulip_1
7f78ee4d5296        rabbitmq:3.5.5                                          "/docker-entrypoint.s"   24 hours ago        Up 24 hours         5672/tcp                                   dockerzulip_rabbitmq_1
b64cbcda30d2        quay.io/sameersbn/redis:latest                          "/sbin/entrypoint.sh"    24 hours ago        Up 24 hours         6379/tcp                                   dockerzulip_redis_1
49f8266b6719        quay.io/galexrt/zulip-postgresql-tsearchextras:latest   "/sbin/entrypoint.sh"    24 hours ago        Up 24 hours         5432/tcp                                   dockerzulip_database_1
c6ea421bdd7e        quay.io/sameersbn/memcached:latest                      "/sbin/entrypoint.sh "   24 hours ago        Up 24 hours         11211/tcp, 11211/udp                       dockerzulip_memcached_1
```
and here is the images list:
```
REPOSITORY                                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
quay.io/galexrt/zulip                            v1.3.7-2            2cc6da6e0f74        2 days ago          761.8 MB
quay.io/sameersbn/redis                          latest              70bbfe1d71d4        3 days ago          196.4 MB
quay.io/sameersbn/memcached                      latest              725d0fe891bc        3 days ago          195.9 MB
quay.io/galexrt/zulip                            v1.3.7-1            a5746fec43b8        13 days ago         664.8 MB
quay.io/galexrt/zulip-postgresql-tsearchextras   latest              fefe2ad5934c        2 weeks ago         232.8 MB
docker.io/rabbitmq                               3.5.5               91fea4a35848        6 weeks ago         182.9 MB
```

**Comment by Galexrt** [comment] 2015-11-10 14:37
@bluesalt There seems to be problem with my `galexrt/zulip-postgresql-tsearchextras` image.

I'll try to give a workaround until it's fixed.

**Comment by Galexrt** [comment] 2015-11-10 14:40
@bluesalt Could you provide a gist with the full log output from docker-compose?
Not the log files inside the container. Thanks.

**Comment by bluesalt** [comment] 2015-11-10 23:52
Sure.  https://gist.github.com/bluesalt/fea84ee81bddc6b92514

**Comment by Galexrt** [comment] 2015-11-11 05:37
@bluesalt Thanks for the logs. I'm looking into it.

**Comment by Galexrt** [comment] 2015-11-11 11:51
@bluesalt I think I fixed the problem. It seems that it is/was a problem in my `galexrt/zulip-postgresql-tsearchextras` image.
Can you repull the `galexrt/zulip-postgresql-tsearchextras` and try again please?

**Comment by bluesalt** [comment] 2015-11-11 15:03
I could not pull the image from quay.io due to the bad network in China. Is it possible for you to put the image in hub.docker.com ? We have several mirrors in China.

**Comment by Galexrt** [comment] 2015-11-11 15:10
@bluesalt I created the repo on hub.docker.com now. The build should be done in about 20 minutes.

**Comment by Galexrt** [comment] 2015-11-11 17:42
@bluesalt I just checked the state on docker hub. The images is ready.

**Comment by bluesalt** [comment] 2015-11-11 23:24
@Galexrt seems the problem is stil there. I even tried a complete fresh containers creations, and the error was still there. And here is the latest log [docker-compolse.log](https://gist.github.com/bluesalt/29a05eb898fff5c65451). 
Here is the images  list
```
REPOSITORY                                       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
quay.io/galexrt/zulip-postgresql-tsearchextras   latest              8881b37b164c        11 hours ago        232.8 MB
quay.io/galexrt/zulip                            v1.3.7-2            2cc6da6e0f74        4 days ago          761.8 MB
quay.io/sameersbn/redis                          latest              70bbfe1d71d4        4 days ago          196.4 MB
quay.io/sameersbn/memcached                      latest              725d0fe891bc        4 days ago          195.9 MB
quay.io/galexrt/zulip                            v1.3.7-1            a5746fec43b8        2 weeks ago         664.8 MB
docker.io/rabbitmq                               3.5.5               91fea4a35848        6 weeks ago         182.9 MB
```

BTW, I managed to pull the image from quay.io through a proxy service.

**Comment by Galexrt** [comment] 2015-11-12 06:24
I pushed a fix for this to the repo. I'll try to test it soon.
I created a docker hub repo for both images.

**Comment by bluesalt** [comment] 2015-11-12 16:12
Awesome!
I used the docker hub image and the message search works now!

**Comment by Galexrt** [comment] 2015-11-12 17:32
@bluesalt That's good to hear! Thanks for the report.

**Comment by xeor** [comment] 2016-03-01 13:05
Did this problem come back? I'm using `quay.io/galexrt/zulip-postgresql-tsearchextras:latest` from now, created `2016-01-28T22:45:37.813858624Z`. And I have the problem now.. Anyone else?

**Comment by xeor** [comment] 2016-04-08 14:32
noone?

**Comment by galexrt** [comment] 2016-04-08 14:48
@xeor Could you please provide logs from Zulip?
Use the command `docker exec -it ZULIP_CONTAINER_NAME cat /var/log/zulip/*` and post the output as a gist.

**Comment by xeor** [comment] 2016-04-14 07:23
Sorry for the delay..

The error I am getting is the same, there isn't any usefull info in the logs:

```
database_1  | ERROR:  function ts_match_locs_array(unknown, text, tsquery) does not exist at character 213
database_1  | HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
database_1  | STATEMENT:  SELECT /* get_old_messages */ anon_1.message_id, anon_1.flags, anon_1.subject, anon_1.rendered_content, anon_1.content_matches, anon_1.subject_matches
database_1  |   FROM ((SELECT message_id, flags, subject, rendered_content, ts_match_locs_array('zulip.english_us_search', rendered_content, plainto_tsquery('zulip.english_us_search', 'test')) AS content_matches, ts_match_locs_array('zulip.english_us_search', escape_html(subject), plainto_tsquery('zulip.english_us_search', 'test')) AS subject_matches
database_1  |   FROM zerver_usermessage JOIN zerver_message ON zerver_usermessage.message_id = zerver_message.id
database_1  |   WHERE user_profile_id = 7 AND (search_tsvector @@ plainto_tsquery('zulip.english_us_search', 'test')) AND message_id <= 0 ORDER BY message_id DESC
database_1  |    LIMIT 50) UNION ALL (SELECT message_id, flags, subject, rendered_content, ts_match_locs_array('zulip.english_us_search', rendered_content, plainto_tsquery('zulip.english_us
_search', 'test')) AS content_matches, ts_match_locs_array('zulip.english_us_search', escape_html(subject), plainto_tsquery('zulip.english_us_search', 'test')) AS subject_matches
database_1  |   FROM zerver_usermessage JOIN zerver_message ON zerver_usermessage.message_id = zerver_message.id
database_1  |   WHERE user_profile_id = 7 AND (search_tsvector @@ plainto_tsquery('zulip.english_us_search', 'test')) AND message_id >= 1 ORDER BY message_id ASC
database_1  |    LIMIT 50)) AS anon_1 ORDER BY message_id ASC
```

If I (inside the database container), execute the command `CREATE EXTENSION tsearch_extras SCHEMA zulip;`, I where getting an error about not finding `/usr/share/postgresql/9.4/extension/tsearch_extras--1.0.sql`. I found this file in the 9.3 directory, so I tried to symlink it.
However, now I am getting the error `ERROR:  incompatible library "/usr/lib/postgresql/9.4/lib/tsearch_extras.so": version mismatch` from postgres.
Weird... How have this worked for others?

I am trying out different things, but I don't have that much time on this (hence the slow updates)... :)

**Comment by galexrt** [comment] 2016-04-14 08:16
@xeor What image version of docker-zulip are you using?
Try to repull both images with (when using quay.io version):
```
docker pull quay.io/galexrt/zulip:1.3.10
docker pull quay.io/galexrt/zulip-postgresql-tsearchextras:latest
```

Please report back if the problem is still existing.

**Comment by xeor** [comment] 2016-04-14 10:20
I was using zulip:v1.3.10 (notice the `v`, it is a different image...). But the new (without `v`) didn't work either. Now I am trying:

* quay.io/galexrt/zulip-postgresql-tsearchextras:latest (Digest: sha256:860a60c25a349738931e712534f87f2b5ac104d723cf59c0c12f7bdb9551fc06)
* quay.io/galexrt/zulip:1.3.10 (Digest: sha256:d548c1b9b1d7ff1fd455c94b03c360d138f036ed92b3d4e1ad3d0e799b0c5696)

Relevant output when starting;

```
zulip_1     | + psql -h database -p 5432 -U zulip                                   
database_1  | ERROR:  permission denied to create role                              
database_1  | STATEMENT:  CREATE USER zulip;                                        
zulip_1     | ERROR:  permission denied to create role                              
zulip_1     | ALTER ROLE                                                            
zulip_1     | ERROR:  database "zulip" already exists                               
database_1  | ERROR:  database "zulip" already exists                               
database_1  | STATEMENT:  CREATE DATABASE zulip OWNER=zulip;                        
zulip_1     | ERROR:  schema "zulip" already exists                                 
database_1  | ERROR:  schema "zulip" already exists                                 
database_1  | STATEMENT:  CREATE SCHEMA zulip AUTHORIZATION zulip;                  
zulip_1     | Creating tsearch_extras extension ...                                 
zulip_1     | + echo 'Creating tsearch_extras extension ...'                        
zulip_1     | + echo 'CREATE EXTENSION tsearch_extras SCHEMA zulip;'                
zulip_1     | + psql -h database -p 5432 -U postgres zulip                          
database_1  | FATAL:  password authentication failed for user "postgres"            
database_1  | DETAIL:  User "postgres" has no password assigned.                    
database_1  |   Connection matched pg_hba.conf line 94: "host all all 0.0.0.0/0 md5"
zulip_1     | psql: FATAL:  password authentication failed for user "postgres"      
zulip_1     | Database structure recreated.                                         
```

Trying to do it manually;

```bash
root@myhost:~/zulip# docker exec -it zulip_database_1 bash
root@c6a54224ca72:/var/lib/postgresql# su - postgres
postgres@c6a54224ca72:~$ psql zulip
psql (9.4.5)
Type "help" for help.

zulip=# CREATE EXTENSION tsearch_extras SCHEMA zulip;
ERROR:  could not stat file "/usr/share/postgresql/9.4/extension/tsearch_extras--1.0.sql": No such file or directory
# created tsearch_extras--1.0.sql symlink from the 9.3 directory
zulip=# CREATE EXTENSION tsearch_extras SCHEMA zulip;
ERROR:  incompatible library "/usr/lib/postgresql/9.4/lib/tsearch_extras.so": version mismatch
DETAIL:  Server is version 9.4, library is version 9.3.
# downloaded and installed `https://dl.dropboxusercontent.com/u/283158365/zuliposs/postgresql-9.4-tsearch-extras_0.1_amd64.deb`
# which I reference to on https://github.com/zulip/zulip/blob/master/README.dev.md
zulip=# CREATE EXTENSION tsearch_extras SCHEMA zulip;
CREATE EXTENSION
```

I am running docker version 1.7.1, maybe that is the problem? :/

**Comment by xeor** [comment] 2016-04-14 13:18
hmm, even tho I where able to create the extension. Test-searchs wont show any results. I'll try tomorrow in case there is some indexing job that needs to run.

**Comment by galexrt** [comment] 2016-04-14 13:40
@xeor I'm going to test this. But currently you seem to be the only one with the problem.

***

@reyman Could you please try the Zulip text search and confirm this problem if you have it too? Would be awesome of you to check if the problem exists. :)

**Comment by reyman** [comment] 2016-04-18 08:36
Hi,
Sorry for delay @galexrt , vacation.
I try zulip last image and text search during this week. I post result here :)

**Comment by galexrt** [comment] 2016-04-23 11:42
I may have pushed a potential fix for this problem.

@xeor Can you please try with the latest version of `quay.io/galexrt/zulip-postgresql-tsearchextras:latest`.
(`docker pull quay.io/galexrt/zulip-postgresql-tsearchextras:latest`)

**Comment by galexrt** [comment] 2016-04-24 12:48
@xeor Could you please try again with the latest docker-zulip version `v1.3.10-1` and check if it's working now? Also repull the `quay.io/galexrt/zulip-postgresql-tsearchextras:latest` image.

**Comment by xeor** [comment] 2016-04-24 12:50
Awesome @galexrt.. I have the setup @ work, but I will see if I am able to do it as soon as possible early the coming week :)

**Comment by reyman** [comment] 2016-05-02 12:52
Hi @galexrt 
Finally i have some time to update my zulip version (to v1.3.10-1).
I make a sudo docker-compose stop, then rm, and repull all images.

When i test the search bar, it doesn't work, i have a circle infinite progress bar and a red error message at right : 

```
Unable to connect to Zulip. Could not fetch messages. 
Retrying soon... 
```

**Comment by galexrt** [comment] 2016-05-02 14:44
@reyman Have you also repulled the `quay.io/galexrt/zulip-postgresql-tsearchextras` image? I had made some changes to it some time ago.

**Comment by galexrt** [comment] 2016-05-08 13:13
Closing as I can't reproduce this problem. If you experience this problem again, please create a new issue. Thanks!

**Closed by galexrt** 2016-05-08 13:13 UTC
Labels: waiting-for-feedback
