### ISSUE TITLE
LDAP backend doesn't work

### ISSUE THREAD

**Issue by Seinth** [Galexrt/docker-zulip#52] opened 2015-12-07 09:21 UTC
Looks like there are some problems with LDAP integration, I can't login to Zulip based on LDAP. 

docker-compose part:
>    - ZULIP_AUTH_BACKENDS=ZulipLDAPAuthBackend
>    - ZULIP_SETTINGS_AUTH_LDAP_SERVER_URI=XXX
>    - ZULIP_SETTINGS_AUTH_LDAP_USER_SEARCH=LDAPSearch("XXX",ldap.SCOPE_SUBTREE, "(mail=%(user)s)")
>    - ZULIP_SETTINGS_AUTH_LDAP_APPEND_DOMAIN=None

What kind of log are needed for debugging?

**Comment by Galexrt** [comment] 2015-12-07 20:01
Can you run, I think it should be `docker exec ZULIP_CONTAINER_NAME cat /var/log/supervisor/*zulip*` and post the output as a gist please. That will help debugging the problem.

**Comment by Galexrt** [comment] 2015-12-07 20:01
Can you run, I think it should be `docker exec ZULIP_CONTAINER_NAME cat /var/log/supervisor/*zulip*` and post the output as a gist please. That will help debugging the problem.

**Comment by Seinth** [comment] 2015-12-08 13:42
https://gist.github.com/Seinth/8bd99e3098d740280dd4

No additional log appear after unsuccessfully login attempt.

**Comment by Galexrt** [comment] 2015-12-08 17:04
@Seinth Can you provide the output of all `zulip-*` log files from the container.
Please run `tail -n +1 /var/log/supervisor/zulip-*` inside the container and post the output.

Could you post your `docker-compose.yml` (without passwords, secrets), so I can take a look at it and see if there's a problem.

**Comment by Seinth** [comment] 2015-12-08 17:27
Other log files are empty (have a look at ls -la output, 5th column contains size). I'll post docker-compose.yml tommorow morning.

**Comment by Seinth** [comment] 2015-12-09 06:58
docker-compose.yml
https://gist.github.com/Seinth/b43fa5e1278cae3e819f

**Comment by Galexrt** [comment] 2015-12-09 08:25
The `ZULIP_AUTH_BACKENDS` must be for LDAP `ZULIP_AUTH_BACKENDS=zproject.backends.ZulipLDAPAuthBackend`, see https://github.com/zulip/zulip/blob/master/zproject/local_settings_template.py#L24.

Also see the wiki page https://github.com/Galexrt/docker-zulip/wiki/Zulip-LDAP-Authentication.
BTW The containers doesn't need to be privileged.

**Comment by Seinth** [comment] 2015-12-09 08:46
Tested, now I'm getting 500:

    500: Internal server error.
    
    Well oops. This one's probably our fault. Sorry about that! Updates on service availability are posted to @ZulipStatus on Twitter.

    If you'd like, you can drop us a line to let us know what happened.

No new logs in /var/log/supervisor

AUTH_BACKEND line in docker composer:
```- ZULIP_AUTH_BACKENDS=zproject.backends.ZulipLDAPAuthBackend```

Container was recreated, stored data were removed.

I'm using privileged mode, because volume is setted to nfs partition.

**Comment by Galexrt** [comment] 2015-12-09 14:03
@Seinth Are you 100% sure there are no new log lines in `/var/log/zulip*` and `/var/log/supervisor/zulip*`?

**Comment by Seinth** [comment] 2015-12-09 14:51
So far I was checking only ```/var/log/supervisor/zulip```
In ```/var/log/zulip``` 4 file changed after access attempt:
https://gist.github.com/Seinth/051eab3430f368a5e515

**Comment by Galexrt** [comment] 2015-12-12 11:40
@Seinth Just that you know, I'm looking into this problem. But a fix will take some time, sry bout that.

**Comment by Galexrt** [comment] 2015-12-12 11:58
BTW I updated the LDAP wiki page https://github.com/Galexrt/docker-zulip/wiki/Zulip-LDAP-Authentication.

I added an env var `ZULIP_LDAP_ENABLED` to enable the configuration of the LDAP settings (Currently in the latest dev image that is being built). You would need to set `ZULIP_LDAP_ENABLED` to `True`. `ZULIP_LDAP_ENABLED` enables the configuration of LDAP from now on.

**Comment by Galexrt** [comment] 2015-12-13 13:47
@Seinth I pushed some changes to the dev branch.
Can you repull the image `quay.io/galexrt/zulip:dev` and try again with the mentioned `ZULIP_LDAP_ENABLED` set to `True`.
Thanks for testing this, I personally don't have an LDAP server to test with.

**Comment by Seinth** [comment] 2015-12-14 13:39
Thanks! But I have bad news:

I pulled new image, stopped and removed containers, clean volume content and execute docker-compose up

Sam error on web site (500).
https://gist.github.com/Seinth/d33876b50a3532cc299e

**Comment by Galexrt** [comment] 2015-12-14 14:21
I think I'll see the error now. `ImportError: No module named zproject.backends`
Thanks for the log. This should be fixed soon.

**Comment by Galexrt** [comment] 2015-12-14 14:25
@Seinth Can you try again with `ZULIP_AUTH_BACKENDS` set to `ZulipLDAPAuthBackend`.

`- ZULIP_AUTH_BACKENDS=ZulipLDAPAuthBackend`

**Comment by Seinth** [comment] 2015-12-14 14:32
Login screen now appear, while trying to log in I got:
```Please enter a correct email and password. Note that both fields may be case-sensitive.```
The only interesting part of log:
https://gist.github.com/Seinth/d310543d6ec9a46ece4f

Do you know where I can look for LDAP log?

**Comment by Seinth** [comment] 2015-12-14 14:39
I was able to get another 500 while trying to "register":
https://gist.github.com/Seinth/6bb07da8a6f6e54ba991

**Comment by Galexrt** [comment] 2015-12-14 20:03
@Seinth In the log https://gist.github.com/Seinth/6bb07da8a6f6e54ba991 the problem is that you didn't configure a working/reachable smtp server. A working smtp server is needed from zulip.

I don't see a problem with docker-zulip in the log https://gist.github.com/Seinth/d310543d6ec9a46ece4f.
I can't really help you with LDAP, because I don't have a LDAP server.
I would therefore advise you to create a ticket at the official zulip/zulip project and ask for help about LDAP authentication problem there.

I'm closing this as I can't really help with what seems like a problem on zulip's side. I hope I could help a bit by fixing the bugs with the image.

**Closed by Galexrt** 2015-12-14 20:03 UTC
Labels: bug, confirmed, in-progress
