### ISSUE TITLE
Too many level of symbolic links

### ISSUE THREAD

**Issue by reyman** [Galexrt/docker-zulip#64] opened 2016-03-26 19:31 UTC
Hi,
Don't know if its linked to my docker or the image but i have this error now when i launch `docker-compose up`

```
zulip_1     | === Begin Initial Configuration Phase ===
zulip_1     | + '[' '!' -d /data ']'
zulip_1     | + '[' '!' -d /data/backups ']'
zulip_1     | + '[' '!' -d /data/certs ']'
zulip_1     | + '[' '!' -d /data/uploads ']'
zulip_1     | + echo 'Preparing and linking the uploads folder ...'
zulip_1     | + rm -rf /home/zulip/uploads
zulip_1     | Preparing and linking the uploads folder ...
zulip_1     | + ln -sfT /data/uploads /home/zulip/uploads
zulip_1     | + chown zulip:zulip -R /data/uploads
zulip_1     | + '[' '!' -d /data/settings ']'
zulip_1     | + '[' '!' -d /data/settings/etc-zulip ']'
zulip_1     | + cp -rf /etc/zulip /data/settings/etc-zulip
zulip_1     | cp: failed to access '/data/settings/etc-zulip': Too many levels of symbolic links
zulip_zulip_1 exited with code 1

```

**Comment by Galexrt** [comment] 2016-03-26 22:07
@reyman Looking into it.

**Comment by Galexrt** [comment] 2016-03-27 09:41
@reyman Can you run `ls -ahl`, `tree --noreport -fp` and `find -L ./ -mindepth 15` in the Zulip data folder  (on the host server). Please post the output as a gist.

Please try to remove the folder `settings` in the Zulip data directory on the server and try to start it again.

**Comment by reyman** [comment] 2016-03-27 12:49
I run the command in `/opt/docker/zulip` : 

```
➜  zulip ls -ahl
total 24K
drwxr-xr-x 6 root   root   4,0K mars  26 19:55 .
drwxr-xr-x 5 root   root   4,0K mars  26 19:55 ..
drwxr-xr-x 2 root   root   4,0K mars  26 19:55 backups
drwxr-xr-x 2 root   root   4,0K mars  26 19:55 certs
drwxr-xr-x 2 root   root   4,0K mars  26 19:55 settings
drwxr-xr-x 2 reyman reyman 4,0K mars  26 19:55 uploads
```

```
➜  zulip tree --noreport -fp
.
├── [drwxr-xr-x]  ./backups
├── [drwxr-xr-x]  ./certs
│   ├── [-rw-r--r--]  ./certs/zulip.combined-chain.crt
│   └── [-rw-r--r--]  ./certs/zulip.key
├── [drwxr-xr-x]  ./settings
│   └── [lrwxrwxrwx]  ./settings/etc-zulip -> /data/settings/etc-zulip
└── [drwxr-xr-x]  ./uploads
```

The last command `find -L ./ -mindepth 15` return nothing 

I remove the `settings` folder, zulip start correctly now, strange...

Another info, when i try to login using ldap, i have the error 500 (i open an issue about that in zulip), and this message. Problem seems to be the user creation.

```
rabbitmq_1  | =INFO REPORT==== 27-Mar-2016::12:46:36 ===
rabbitmq_1  | accepting AMQP connection <0.454.0> (172.17.0.7:59800 -> 172.17.0.5:5672)
zulip_1     | 2016-03-27 12:46:37,277 INFO exited: zulip-postsetup-create_user (exit status 0; expected)
```

**Comment by Galexrt** [comment] 2016-03-27 13:30
@reyman Can you check if the `/etc/zulip/settings.py` in the container is filled properly at the bottom with your settings? If the settings are there, the issue is "fixed".

**Comment by reyman** [comment] 2016-03-27 16:26
Hi @Galexrt ,
seems ok in settings.py

**Comment by reyman** [comment] 2016-03-27 16:31
@Galexrt I continue to have this error 

`zulip_1     | 2016-03-27 16:29:15,957 INFO exited: zulip-postsetup-create_user (exit status 0; expected)  
`
Settings.py contain double env.

**Comment by reyman** [comment] 2016-03-27 16:33
To be sure, i rm all zulip files, images, and repull.

**Comment by Galexrt** [comment] 2016-03-27 17:52
```
2016-03-27 16:37:13,911 INFO exited: zulip-postsetup-create_user (exit status 0; expected)
```
@reyman This is not an error. The user should be created.
Please create a gist with your current `docker-compose.yml` here (without sensitive data), so I can see what user will be created.

**Comment by reyman** [comment] 2016-03-27 19:02
Oki sorry, i misread the message.

https://gist.github.com/87dc3b3fda30b543cc4c

**Comment by Galexrt** [comment] 2016-03-27 19:15
@reyman Are you sure you removed your email_password?

**Comment by reyman** [comment] 2016-03-27 19:28
@Galexrt it's not the direct password, but an application password, but you're right. I remove the password. 
https://gist.github.com/0a1cb49b63629edd9a3b

**Comment by reyman** [comment] 2016-03-27 19:36
@Galexrt Some news in https://github.com/zulip/zulip/issues/210 , but i'm not sure i can hardcode something in the docker image. Can i stop, modify and rerun with the modification proposed by @timabbot do you think ?

**Comment by Galexrt** [comment] 2016-03-27 21:21
@reyman Could you explain the proposed modification by timabbot for me please? I don't really get what I need to fix in the image.

**Comment by Galexrt** [comment] 2016-03-27 21:29
@reyman I'm closing this in favor of https://github.com/zulip/zulip/issues/210.
When timabbot explains the proposed modification to me, I will directly implement the fix in the dev branch and later push a new release.

**Closed by Galexrt** 2016-03-27 21:29 UTC

**Comment by reyman** [comment] 2016-03-27 22:03
He add some more explanations for the hack in https://github.com/zulip/zulip/issues/210

**Comment by Galexrt** [comment] 2016-03-27 22:13
@reyman You can remove the `ZULIP_LDAP_ENABLED: "True"`.

**Comment by Galexrt** [comment] 2016-03-27 22:20
@reyman I posted a comment on https://github.com/zulip/zulip/issues/210.
